### ISSUE TITLE
(CRT-A0017) Types of function parameters can be combined

### ISSUE THREAD

**Issue by alextwothousand** [sampgo/sampgo#2]
## Description
If function parameters of the same type lie next to each other, it&#x27;s better to mention their type at the end of the last parameter. Unlike other languages, like C, where all parameters must be specified with types explicitly, it is not required to do so in Go, and is …

## Occurrences
There are 199 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/sampgo/sampgo/issue/CRT-A0017/occurrences/](https://deepsource.io/gh/sampgo/sampgo/issue/CRT-A0017/occurrences/)

**Comment by devlexanderxyz** [comment]
Will work on this when necessary to do so.
